name: Code quality checks

on:
  workflow_call:
  push:
    branches: [ main ]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.0'
        
      - name: Install golint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2
    
      - name: Install gocyclo
        run: go install github.com/fzipp/gocyclo/cmd/gocyclo@latest

      - name: Install goimports 
        run: go install golang.org/x/tools/cmd/goimports@latest
    
      - name: Run pre-commit checks
        uses: pre-commit/action@v2.0.3        
